spring.application.name=gestionfinancierapersonal

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.fplpimbgmrzxssaqpwpo
spring.datasource.password=CAMBIAR_PASSWORD

resend.api.key=CAMBIAR_CLAVE

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

